name: Release Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Run all scripts
        run: |
          npm run all

      - name: Bump version
        run: |
          npm version patch -m "Bump version to %s"
          npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_TOKEN }}

      - name: set up git
        run: |
          git config --global user.email "mohamed.sarwat.000@gmail.com"
          git config --global user.name "mohamedtharwat000"
          git commit -am "Bump version" --no-edit

      - name: publish
        run: npm publish
