name: Release Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Run all scripts
        run: |
          npm run all

      - name: Configure Git
        run: |
          git config --global user.email "mohamed.sarwat.000@gmail.com"
          git config --global user.name "mohamedtharwat000"
          npm version patch -m "Bump version to %s"
          git push -a

      - name: Log in to npm with token
        run: npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_TOKEN }}

      - name: Bump version and publish
        run: |
          npm publish
