name: Release Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Run all scripts
        run: |
          npm run all

      - name: Bump version and publish
        run: |
          git config --global user.email "mohamed.sarwat.000@gmail.com"
          git config --global user.name "mohamedtharwat000"
          if [ -z "$(git status --porcelain)" ]; then
          else
            git add .
            git commit -m "Bump version"
          fi
          npm version patch --force -m "Bump version to %s"
          git push

      - name: Publish to npm registry
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
