name: Release Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Run all scripts
        run: |
          npm run all

      - name: Check if commit message contains version bump
        id: version-check
        run: |
          if grep -qE '^Bump version to [0-9]+\.[0-9]+\.[0-9]+' $GITHUB_EVENT_PATH; then
            echo "should_run=true" >> $GITHUB_ENV
          else
            echo "should_run=false" >> $GITHUB_ENV
          fi

      - name: Bump version and publish
        if: steps.version-check.outputs.should_run == 'true'
        run: |
          npm version patch -m "Bump version to %s"
          git config --global user.email "mohamed.sarwat.000@gmail.com"
          git config --global user.name "mohamedtharwat000"
          git commit -am "Bump version" --no-edit
          npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_TOKEN }}
          npm publish
